#define _USE_MATH_DEFINES
#include <cmath>
#include <opencv2/core/core.hpp>
#include <opencv2/core/mat.hpp>
#include <opencv2/core/Point.hpp>
#include <opencv2/core/Rect.hpp>
#include <opencv2/core/Scalar.hpp>
#include <opencv2/highgui/Highgui.hpp>
#include <opencv2/objdetect/objdetect.hpp>
